<a href="https://colab.research.google.com/github/ekramasif/AI-Lab-Final-Project/blob/main/Extraa/Data_Preprocessing_Tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Google Drive Mount

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Datasets/Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[15624510 'Male' 19 19000]
 [15810944 'Male' 35 20000]
 [15668575 'Female' 26 43000]
 ...
 [15654296 'Female' 50 20000]
 [15755018 'Male' 36 33000]
 [15594041 'Female' 49 36000]]


In [ ]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[[15624510 'Male' 19 19000]
 [15810944 'Male' 35 20000]
 [15668575 'Female' 26 43000]
 ...
 [15654296 'Female' 50 20000]
 [15755018 'Male' 36 33000]
 [15594041 'Female' 49 36000]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 1.0 15624510 19 19000]
 [0.0 1.0 15810944 35 20000]
 [1.0 0.0 15668575 26 43000]
 ...
 [1.0 0.0 15654296 50 20000]
 [0.0 1.0 15755018 36 33000]
 [1.0 0.0 15594041 49 36000]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[1.0 0.0 15699284 29 28000]
 [1.0 0.0 15599081 45 22000]
 [0.0 1.0 15747043 46 117000]
 ...
 [0.0 1.0 15706071 51 23000]
 [0.0 1.0 15646227 46 79000]
 [0.0 1.0 15689425 30 49000]]


In [ ]:
print(X_test)

[[0.0 1.0 15755018 36 33000]
 [1.0 0.0 15697020 39 61000]
 [0.0 1.0 15796351 36 118000]
 [0.0 1.0 15665760 39 122000]
 [1.0 0.0 15794661 26 118000]
 [1.0 0.0 15717560 38 65000]
 [1.0 0.0 15680243 20 36000]
 [0.0 1.0 15596522 49 89000]
 [0.0 1.0 15669656 31 18000]
 [0.0 1.0 15638646 48 141000]
 [1.0 0.0 15644296 34 72000]
 [1.0 0.0 15629885 39 73000]
 [0.0 1.0 15674206 35 72000]
 [1.0 0.0 15575247 48 131000]
 [1.0 0.0 15611191 53 82000]
 [0.0 1.0 15685346 56 133000]
 [0.0 1.0 15774744 60 83000]
 [0.0 1.0 15728773 27 58000]
 [1.0 0.0 15667265 28 87000]
 [0.0 1.0 15593715 60 102000]
 [1.0 0.0 15724423 40 75000]
 [1.0 0.0 15780572 50 88000]
 [1.0 0.0 15715622 44 139000]
 [0.0 1.0 15622478 47 43000]
 [0.0 1.0 15617482 45 26000]
 [0.0 1.0 15809823 26 15000]
 [1.0 0.0 15574372 58 47000]
 [0.0 1.0 15708196 49 74000]
 [1.0 0.0 15778830 53 34000]
 [1.0 0.0 15794566 52 114000]
 [0.0 1.0 15668385 39 42000]
 [0.0 1.0 15804002 19 76000]
 [1.0 0.0 15578738 18 86000]
 [0.0 1.0 15727467 57 74000]
 [1.0

In [ ]:
print(y_train)

[0 1 1 0 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0
 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 1 0 0 0 1 0 1 1 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1
 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1
 0 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1
 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1
 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1
 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1
 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0]


In [ ]:
print(y_test)

[0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0
 0 1 0 1 1 0 0 1 1 1 1 0 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0
 0 1 0 0 0 0]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[1.0 0.0 15699284 -0.8033008104771288 -1.1912179543545012]
 [1.0 0.0 15599081 0.7569799746681295 -1.368598012704171]
 [0.0 1.0 15747043 0.8544975237397081 1.4399195778322673]
 ...
 [0.0 1.0 15706071 1.3420852690976013 -1.3390346696458928]
 [0.0 1.0 15646227 0.8544975237397081 0.31651254161769204]
 [0.0 1.0 15689425 -0.7057832614055501 -0.5703877501306569]]


In [ ]:
print(X_test)

[[0.0 1.0 15755018 -0.12067796697607829 -1.0434012390631098]
 [1.0 0.0 15697020 0.17187468023865762 -0.21562763343131733]
 [0.0 1.0 15796351 -0.12067796697607829 1.4694829208905458]
 [0.0 1.0 15665760 0.17187468023865762 1.587736293123659]
 [1.0 0.0 15794661 -1.0958534576918646 1.4694829208905458]
 [1.0 0.0 15717560 0.074357131167079 -0.09737426119820415]
 [1.0 0.0 15680243 -1.6809587521213365 -0.9547112098882748]
 [0.0 1.0 15596522 1.147050170954444 0.6121459722004751]
 [0.0 1.0 15669656 -0.6082657123339715 -1.4868513849372842]
 [0.0 1.0 15638646 1.0495326218828653 2.1494398112309465]
 [1.0 0.0 15644296 -0.3157130651192356 0.10956914020974394]
 [1.0 0.0 15629885 0.17187468023865762 0.13913248326802224]
 [0.0 1.0 15674206 -0.21819551604765694 0.10956914020974394]
 [1.0 0.0 15575247 1.0495326218828653 1.8538063806481635]
 [1.0 0.0 15611191 1.5371203672407585 0.4052025707925269]
 [0.0 1.0 15685346 1.8296730144554945 1.9129330667647202]
 [0.0 1.0 15774744 2.219743210741809 0.4347659138508